#!/bin/bash
# --------------------------------------------------------------------------
# Installationsdatei für den Pi0: RTSP-Server installieren
#
# Author: Bernhard Bablok, Benjamin Zeussel
# License: GPL3
#
# Website: https://github.com/bablokb/pi-wsa
#
# --------------------------------------------------------------------------

PACKAGES="liblog4cpp5-dev liblivemedia-dev cmake"

# --- basic packages   ------------------------------------------------------

check_packages() {
  local p
  for p in "$@"; do
    echo -en "Checking $p ... " >&2
    dpkg -s "$p" 2>/dev/null | grep -q "Status.*ok" || return 0
    echo "ok" >&2
  done
  return 1
}

install_packages() {
  if [ -n "$PACKAGES" ] && check_packages $PACKAGES; then
    echo -e "[INFO] installing additional packages" 2>&1
    apt-get update
    apt-get -y install $PACKAGES
  fi
}

# --- install specific files   ----------------------------------------------

install_files() {
  echo -e "[INFO] Installiere Projektdateien" 2>&1

  rand="$RANDOM"
  if [ -f /etc/asound.conf ]; then
    # save current configuration
    mv /etc/asound.conf /etc/asound.conf.$rand
  fi

  for f in `find $(dirname "$0")/../files.pi0/ -type f`; do
    cp "$f" "${f#*files.pi0}"
    chown root:root "${f#*files.pi0}"
  done

  chmod 755 /usr/local/bin/h264_v4l2_rtspserver
  chmod 644 /etc/asound.conf
  chmod 644 /etc/systemd/system/rtsp.service

  # restore old configuration
  if [ -f /etc/asound.conf.$rand ]; then
    mv -f /etc/asound.conf /etc/asound.conf.new
    mv /etc/asound.conf.$rand /etc/asound.conf
    echo -e "[INFO] Neue Version der asound.conf gesichert als: /etc/asound.conf.new" 2>&1
  fi
}

# --- configure system   ----------------------------------------------------

configure_system() {
  # update /etc/modules
  if ! grep -q "^bcm2835-v4l2" /etc/modules; then
    echo -e "[INFO] Konfiguriere /etc/modules" 2>&1
    echo "bcm2835-v4l2" >> /etc/modules
  fi
}


# --- install v4l2rtspserver from Source(Github) ----------------------------
install_v4l2rtspserver(){
  read -p "Soll v4l2rtspserver und libv4l2cpp aus den Github-Quellen installiert werden? " -n 1 -r
  if[[ $REPLY =~ ^[YyJj]$ ]]
  then
    
    # install libasoun required for audio
    sudo apt install libasound2-dev
    # install libv4l2cpp
    echo -e "[INFO] Installiere libv4l2cpp" 2>&1
    cd ~/
    git clone https://github.com/mpromonet/libv4l2cpp.git
    cd libv4l2cpp/
    make
    sudo mkdir /usr/include/libv4l2cpp/
    sudo make install
    
    # install v4l2rtspserver
    echo -e "[INFO] Installiere v4l2rtspserver" 2>&1
    cd ~/
    git clone https://github.com/mpromonet/v4l2rtspserver.git
    cd v4l2rtspserver/
    echo -e "[INFO] Start des Build-Prozesses, dass kann jetzt ein wenig dauern ;-)" 2>&1
    cmake . && make
    sudo make install
  fi
}

# --- main program   --------------------------------------------------------

install_packages
install_files
configure_system
install_v4l2rtspserver
